# Use uma imagem de base que tenha o Node.js instalado
FROM node:14

# Crie um diretório de trabalho no contêiner
WORKDIR /app

# Instale o Vite globalmente no contêiner
RUN npm install -g create-vite

# Copie os arquivos do seu aplicativo para o contêiner
COPY . .

# Instale as dependências do aplicativo (se você tiver um package.json)
RUN npm install

# Exponha a porta em que o aplicativo Vite será executado (geralmente é a porta 3000)
EXPOSE 3000

# Comando para iniciar o aplicativo Vite
CMD ["vite", "dev"]
