version: '3'
services:
  # Laravel PHP-FPM container
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hdcevents
    ports:
      - "3316:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

  app:
    image: disgrama:lts
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    command: bash -c "php artisan migrate && php artisan serve --host=0.0.0.0 --port=9000"
    networks:
      - laravel
    depends_on:
      - db

  vite:
      image: node:14
      ports:
        - "5173:5173"
      working_dir: /var/www/html
      volumes:
        - .:/var/www/html
      command: yarn dev
      networks:
        - laravel

  # MySQL container


networks:
  laravel:
