version: '3'
services:
  app:
    image: disgrama_o_retorno
    container_name: laravel_app
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - .:/var/www/html # Substitua 'seu_projeto' pelo diretório do seu projeto Laravel
    networks:
      - laravel
    command: php artisan serve --host=127.0.0.1 --port=8000


  # MySQL container
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hdcevents
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    ports:
      - "3316:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - laravel

networks:
  laravel:
