version: '3.7'

services:
  mysql:
    image: meu-mysql
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    command: --init-file /docker-entrypoint-initdb.d/dump.sql
